##########################################
###### use this file in the profile ######
##########################################

# use multilib packages; x86_64 only
multilib="true"

displaymanager="lightdm" # O DE escolhido instalará o seu próprio DM

# Configurações do LiveCD
autologin="true"
hostname="bigcommunity"
username="community"
password="big"
login_shell=/bin/bash
addgroups="lp,network,power,wheel,tty,audio"

# Label do ISO
label="BigCommunity-Core.iso"

################ install ################
# Habilita o modo de instalação via rede
netinstall="true"

# Não usa o unpackfs, pois os pacotes serão baixados
chrootcfg="false"

# Usa GeoIP para localização
geoip='true'

# Serviços a serem habilitados no sistema INSTALADO (o DM será instalado pela lista de pacotes)
enable_systemd=('bluetooth' 'cronie' 'ModemManager' 'NetworkManager' 'cups' 'fstrim.timer' 'pkgfile-update.timer' 'vboxservice' 'ufw' 'avahi-daemon' 'smb' 'cups-browsed')

# Serviços a serem DESABILITADOS no ambiente LIVE
disable_systemd_live=('pacman-init' 'ufw' 'fstrim.timer' 'big-btrfs-balance' 'auto-unlock-pacman')
